export const IS_DEMO_MODE = true;

export function getMockResponse(prompt: string): string {
  const p = prompt.toLowerCase();
  
  if (p.includes("taj mahal")) {
    return "A teardrop on the cheek of time, the Taj Mahal is an enduring testament to love and loss.\n\nCommissioned in 1632 by the Mughal emperor Shah Jahan to house the tomb of his favorite wife, Mumtaz Mahal, this ivory-white marble mausoleum on the right bank of the river Yamuna in Agra remains one of the world's most universally admired masterpieces.\n\n**Architecture & Significance**\nThe Taj Mahal complex is believed to have been completed in its entirety in 1653 at a cost estimated at the time to be around 32 million rupees. It was designed by a board of architects under imperial supervision, including Ustad Ahmad Lahauri, who is generally considered to be the principal designer. The architectural style perfectly blends Indian, Persian, and Islamic elements, characterized by perfect symmetry, the massive central dome, and the four minarets framing the tomb.\n\n🏛️ **Did You Know?**\nThe minarets of the Taj Mahal were built leaning slightly outward. This was a deliberate architectural choice so that in the event of an earthquake, they would fall away from the main tomb rather than crashing into the central dome!";
  }
  
  if (p.includes("konark") || p.includes("sun temple")) {
    return "A colossal chariot frozen in stone, the Konark Sun Temple was designed to carry the Sun God across the heavens.\n\nBuilt in the 13th century (c. 1250 CE) by King Narasimhadeva I of the Eastern Ganga dynasty, this monumental temple in Odisha is dedicated to the Hindu sun god Surya.\n\n**Architecture & Significance**\nThe temple is uniquely shaped like a gigantic chariot with 24 elaborately carved stone wheels, some nearly 3 meters in diameter, pulled by seven life-sized horses. The architecture is a masterpiece of the Kalinga style. Originally, the main sanctum tower (shikhara) was over 200 feet tall, making it one of the tallest structures in India at the time, though it has since collapsed. The intricate carvings cover every inch of the structure, depicting daily life, mythical creatures, and divine beings.\n\n🏛️ **Did You Know?**\nThe 24 wheels of the Konark Sun Temple act as precise sundials. The spokes of the wheels cast shadows that can be used to calculate the exact time of day down to the minute!";
  }

  if (p.includes("hampi") || p.includes("vijayanagara")) {
    if (p.includes("what if")) {
      return "**What if the Vijayanagara Empire had survived?**\n\n**⚔️ Historical Reality**\nIn 1565, the Vijayanagara Empire suffered a catastrophic defeat at the Battle of Talikota against the combined forces of the Deccan Sultanates. The magnificent capital city of Hampi was subsequently sacked, looted, and reduced to ruins over several months, marking the beginning of the end for the empire.\n\n**🌀 The Alternate Possibility**\nIf Rama Raya had employed different military tactics or prevented the alliance of the Sultanates, Vijayanagara might have won or at least survived the battle. The empire could have continued to thrive as the dominant power in Southern India, serving as a bastion of Hindu culture and a major center for global trade.\n\n**🌍 Likely Consequences**\nHampi would not be a city of ruins today, but a sprawling, continuously inhabited metropolis rivaling Rome or Kyoto in its layered historical architecture. The empire might have successfully resisted early European colonial incursions, potentially altering the course of the British East India Company's expansion. South Indian art, literature, and temple architecture would have seen continued, uninterrupted patronage, evolving into even more complex forms.";
    }
    return "Amidst a surreal landscape of giant boulders, the ruins of Hampi whisper tales of one of the greatest empires in Indian history.\n\nLocated in Karnataka, Hampi was the magnificent capital of the Vijayanagara Empire, which flourished from the 14th to the 16th century. At its peak, it was one of the largest and wealthiest cities in the world, attracting traders from Portugal, Persia, and beyond.\n\n**Architecture & Significance**\nThe site comprises over 1,600 surviving remains, including sacred temples, royal complexes, riverside features, and market streets. The architecture reflects a highly developed aesthetic sense, blending Dravidian temple architecture with Indo-Islamic elements in the royal and civic buildings. The Virupaksha Temple, with its towering gopuram, and the Vittala Temple, famous for its musical pillars and iconic stone chariot, are masterpieces of this era.\n\n🏛️ **Did You Know?**\nThe Vittala Temple in Hampi features 56 musical pillars (also known as SaReGaMa pillars). When tapped gently, these solid granite pillars produce the sounds of different Indian classical musical instruments!";
  }

  if (p.includes("brihadeeswara") || p.includes("tanjore") || p.includes("thanjavur")) {
    return "A millennium after its consecration, the Brihadeeswara Temple still dominates the skyline and the imagination, an unyielding mountain of granite.\n\nCompleted in 1010 CE by the great Chola emperor Rajaraja I in Thanjavur, Tamil Nadu, this temple is one of the most magnificent architectural achievements in Indian history and a UNESCO World Heritage site.\n\n**Architecture & Significance**\nDedicated to Lord Shiva, the temple is a prime example of fully realized Dravidian architecture. The main vimana (tower) is incredibly tall, reaching 66 meters (216 feet), and is topped by a massive monolithic cupola carved from a single piece of granite weighing an estimated 80 tons. The fact that the temple was built entirely of granite—a material not found locally and extremely difficult to carve—adds to its mystique.\n\n🏛️ **Did You Know?**\nTo place the massive 80-ton granite capstone on top of the 216-foot tower, historians believe the Cholas constructed a gentle earthen ramp that started several kilometers away, utilizing a technique similar to how the Egyptian pyramids were built!";
  }

  if (p.includes("what if") && p.includes("ashoka")) {
    return "**What if Ashoka never embraced Buddhism?**\n\n**⚔️ Historical Reality**\nAfter the remarkably bloody Kalinga War around 260 BCE, Emperor Ashoka of the Maurya Dynasty was consumed by remorse. This led to his profound transformation, embracing Buddhism and propagating the principles of Dhamma (non-violence, tolerance, and compassion) across his vast empire through his famous rock and pillar edicts.\n\n**🌀 The Alternate Possibility**\nHad Ashoka remained a relentless conqueror, unaffected by the carnage of Kalinga, he might have continued his military campaigns. The Mauryan Empire could have expanded further south into the Tamil regions or pushed its western borders deeper into the Hellenistic world.\n\n**🌍 Likely Consequences**\nWithout Ashoka's imperial patronage, Buddhism might have remained a relatively minor regional sect in the Ganges plain rather than spreading across Asia to become a major world religion. Furthermore, India would have lost its earliest cohesive framework of civic morality and state-sponsored welfare, potentially leading to a more fractured and continuously warring subcontinent in the centuries that followed.";
  }

  if (p.includes("hidden") || p.includes("secret")) {
    return "History is often written in the shadows, hidden within the very stones of our greatest monuments.\n\nThroughout India's architectural heritage, builders embedded secrets meant only for the initiated, or perhaps as quiet acts of defiance or humor.\n\n**Architectural Secrets**\nMany ancient temples feature intricate interlocking stone mechanisms that require no mortar, designed to withstand devastating earthquakes. Subterranean passages are common, such as those beneath the Red Fort or the forgotten stepwells of Gujarat, serving as escape routes or cool summer retreats. In places like Lepakshi, you can find the famous 'Hanging Pillar' which does not fully rest on the ground, a testament to the master builders' understanding of weight distribution.\n\n🏛️ **Did You Know?**\nIn the ancient Padmanabhaswamy Temple in Kerala, there are several subterranean vaults. Vault B remains unopened and is said to be protected by a Naga Bandham (serpent spell). It has never been breached in modern times, keeping its secrets (and potentially vast treasures) perfectly hidden!";
  }

  if (p.includes("timeline")) {
    return "India's architectural timeline is a breathtaking journey through millennia of faith, power, and innovation.\n\n**The Ancient Foundations (c. 3000 BCE – 500 CE)**\nBeginning with the sophisticated urban planning and baked brick architecture of the Indus Valley Civilization, the timeline progresses to the Mauryan period, notable for Ashoka's polished sandstone pillars and the early rock-cut architecture of the Barabar Caves. The period culminates in the magnificent Buddhist stupas like Sanchi and the intricate rock-cut temples of Ajanta.\n\n**The Classical & Medieval Era (c. 500 CE – 1500 CE)**\nThis era saw the explosive growth of structural Hindu temples. The Guptas laid the foundations, leading to the towering Shikharas of North India (Nagara style, like Khajuraho) and the sprawling temple cities of South India (Dravidian style, like the Brihadeeswara Temple). The Vijayanagara Empire represents the climax of this continuous tradition.\n\n**The Islamic & Syncretic Synthesis (c. 1100 CE – 1800 CE)**\nThe arrival of Islamic dynasties introduced the true arch, the dome, and vast courtyards. The Delhi Sultanate established early Indo-Islamic architecture (Qutub Minar), which eventually flowered into the unparalleled elegance of Mughal architecture (Taj Mahal, Red Fort), beautifully synthesizing Persian aesthetics with indigenous Indian craftsmanship.\n\n🏛️ **Did You Know?**\nThe transition from rock-cut to structural temples didn't happen overnight. The Kailasa Temple at Ellora (8th century) bridges this gap—it is a massive structural-looking temple that was actually carved top-down out of a single solid basalt cliff!";
  }

  if (p.includes("built") || p.includes("who") || p.includes("why")) {
    return "Monuments are rarely the product of a single mind; they are the crystallized ambitions of entire civilizations.\n\nThe question of 'who built it' often reveals a complex interplay between a visionary patron, a master architect, and thousands of nameless artisans.\n\n**Patrons and Purpose**\nGreat structures were typically commissioned for three main reasons: divine merit, political legitimation, or eternal remembrance. When Rajaraja Chola built the Brihadeeswara Temple, it was both a profound act of devotion to Shiva and a massive display of the Chola empire's wealth and logistical capability. When Shah Jahan commissioned the Taj Mahal, it was an unprecedented monument of grief, yet also a statement of Mughal imperial power and aesthetic refinement.\n\n🏛️ **Did You Know?**\nWhile the names of the emperors who commissioned these monuments are famous, we sometimes know the architects too. For instance, the chief architect of the Taj Mahal is widely considered to be Ustad Ahmad Lahauri. In contrast, the master architect of the Brihadeeswara Temple, Kunjara Mallan Rajaraja Perunthachan, proudly inscribed his name on the temple walls, a rarity in ancient Indian architecture!";
  }

  // Fallback response for unhandled queries
  return "That is a fascinating inquiry into our rich heritage.\n\nWhile I am currently operating in a specialized demonstration mode, the tapestry of Indian history is vast and deeply interconnected. From the ancient Indus Valley to the grand empires of the Cholas, Mughals, and Marathas, every stone tells a story of human ambition, artistic devotion, and architectural genius.\n\n**Exploring Further**\nI invite you to ask about specific landmarks like the **Taj Mahal**, the **Brihadeeswara Temple**, **Konark**, or **Hampi**. You can also ask me about **architectural secrets**, request a **timeline**, or explore speculative history by asking a **'What if?'** question (e.g., 'What if the Vijayanagara Empire had survived?').\n\n🏛️ **Did You Know?**\nIndia is home to 42 UNESCO World Heritage Sites as of 2023, encompassing diverse categories from ancient rock shelters and mountain railways to grand temple complexes and entire historic cities!";
}
